// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: zkOracle.proto

package zkOracle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OracleNodeClient is the client API for OracleNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OracleNodeClient interface {
	SendVote(ctx context.Context, in *SendVoteRequest, opts ...grpc.CallOption) (*SendVoteResponse, error)
}

type oracleNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewOracleNodeClient(cc grpc.ClientConnInterface) OracleNodeClient {
	return &oracleNodeClient{cc}
}

func (c *oracleNodeClient) SendVote(ctx context.Context, in *SendVoteRequest, opts ...grpc.CallOption) (*SendVoteResponse, error) {
	out := new(SendVoteResponse)
	err := c.cc.Invoke(ctx, "/zkOracle.OracleNode/SendVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OracleNodeServer is the server API for OracleNode service.
// All implementations must embed UnimplementedOracleNodeServer
// for forward compatibility
type OracleNodeServer interface {
	SendVote(context.Context, *SendVoteRequest) (*SendVoteResponse, error)
	mustEmbedUnimplementedOracleNodeServer()
}

// UnimplementedOracleNodeServer must be embedded to have forward compatible implementations.
type UnimplementedOracleNodeServer struct {
}

func (UnimplementedOracleNodeServer) SendVote(context.Context, *SendVoteRequest) (*SendVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVote not implemented")
}
func (UnimplementedOracleNodeServer) mustEmbedUnimplementedOracleNodeServer() {}

// UnsafeOracleNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OracleNodeServer will
// result in compilation errors.
type UnsafeOracleNodeServer interface {
	mustEmbedUnimplementedOracleNodeServer()
}

func RegisterOracleNodeServer(s grpc.ServiceRegistrar, srv OracleNodeServer) {
	s.RegisterService(&OracleNode_ServiceDesc, srv)
}

func _OracleNode_SendVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleNodeServer).SendVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zkOracle.OracleNode/SendVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleNodeServer).SendVote(ctx, req.(*SendVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OracleNode_ServiceDesc is the grpc.ServiceDesc for OracleNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OracleNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zkOracle.OracleNode",
	HandlerType: (*OracleNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVote",
			Handler:    _OracleNode_SendVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zkOracle.proto",
}
